spring:
  application:
    name: crush-connect

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/college_crush}
    username: ${DB_USER:root}
    password: ${DB_PASS:root}

    hikari:
      maximum-pool-size: 3
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASS}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: ${JWT_SECRET}
  expiration-hours: 24


#spring:
#  application:
#    name: crush-connect
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/college_crush
#    username: root
#    password: root
#
#  jpa:
#    hibernate:
#      ddl-auto: none
#    show-sql: true
#
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ksucheth03@gmail.com
#    password: vlgxvuvfjhoowkyc
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#
#jwt:
#  secret: QnJmKX4H0sM9R+9ZkA2P5rXW8m9nU3Hc0E4T7LJbM2Y=
#  expiration-hours: 24
